apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: contatos-app
type: Opaque
data:
  # Credenciais do PostgreSQL
  POSTGRES_USER: Y29udGF0b3M=  # contatos em base64
  POSTGRES_PASSWORD: Y29udGF0b3M=  # contatos em base64
  POSTGRES_CONNECTION: U2VydmVyPXBvc3RncmVzO1BvcnQ9NTQzMjtEYXRhYmFzZT1jb250YXRvcztVc2VyIElkPWNvbnRhdG9zO1Bhc3N3b3JkPWNvbnRhdG9zOw==
  
  # Credenciais do MongoDB
  MONGO_USER: Y29udGF0b3M=  # contatos em base64
  MONGO_PASSWORD: Y29udGF0b3M=  # contatos em base64
  MONGODB_CONNECTION: bW9uZ29kYjovL2NvbnRhdG9zOmNvbnRhdG9zQG1vbmdvZGI6MjcwMTcvY29udGF0b3M/YXV0aFNvdXJjZT1jb250YXRvcw==
  
  # Credenciais do RabbitMQ
  RABBITMQ_USER: YWRtaW4=  # admin em base64
  RABBITMQ_PASSWORD: Y29udGF0b3M=  # contatos em base64 