version: '3'
services:
  
  cadastro-contatos-api:
    container_name: cadastro-contatos-api
    depends_on:
      - contatos-db
      - prometheus
    build:
      context: ../
      dockerfile: ./src/Services/Contatos.Cadastro.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  
  consulta-contatos-api:
    container_name: consulta-contatos-api
    depends_on:
      - contatos-db-leitura
      - prometheus
    build:
      context: ../
      dockerfile: ./src/Services/Contatos.Consulta.Api/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  contatos-db:
    image: postgres:latest
    container_name: contatos-db
    environment:
      POSTGRES_USER: contatos
      POSTGRES_PASSWORD: contatos
      POSTGRES_DB: contatos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=root
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - prometheus

  contatos-db-leitura:
    image: mongo:latest
    container_name: contatos-db-leitura
    environment:
      MONGO_INITDB_ROOT_USERNAME: contatos
      MONGO_INITDB_ROOT_PASSWORD: contatos
      MONGO_INITDB_DATABASE: contatos
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: contatos
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  grafana_data:
  mongo_data:
  rabbitmq_data: