global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadastro-contatos-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'cadastro-contatos-api:8080' ]

  - job_name: 'consulta-contatos-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'consulta-contatos-api:8080' ]