global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'contatos-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'contatos-api:8080' ]

  - job_name: 'contatos-api-health'
    metrics_path: '/metrics/health'
    static_configs:
      - targets: [ 'contatos-api:8080' ]
