apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastro-contatos-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cadastro-contatos-api
  template:
    metadata:
      labels:
        app: cadastro-contatos-api
    spec:
      containers:
      - name: cadastro-contatos-api
        image: cadastro-contatos-api:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cadastro-api-config
        - secretRef:
            name: postgres-credentials
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5