apiVersion: v1
kind: Service
metadata:
  name: cadastro-contatos-api
spec:
  selector:
    app: cadastro-contatos-api
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP