apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'cadastro-api'
        static_configs:
          - targets: ['cadastro-contatos-api:8080']
        metrics_path: /metrics

      - job_name: 'consulta-api'
        static_configs:
          - targets: ['consulta-contatos-api:8080']
        metrics_path: /metrics

      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus:9090'] 