apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: contatos-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'cadastro-contatos-api'
        static_configs:
          - targets: ['cadastro-contatos-api:8080']
      - job_name: 'consulta-contatos-api'
        static_configs:
          - targets: ['consulta-contatos-api:8080'] 