apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: contatos-app
spec:
  selector:
    app: prometheus
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  type: ClusterIP 