apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-contatos-api
  namespace: contatos-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consulta-contatos-api
  template:
    metadata:
      labels:
        app: consulta-contatos-api
    spec:
      containers:
      - name: consulta-contatos-api
        image: pedrobaraof/consulta-contatos-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: MongoDB__ConnectionString
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: MONGODB_CONNECTION
        - name: RabbitMQ__Host
          value: "rabbitmq"
        - name: RabbitMQ__Username
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: RABBITMQ_USER
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: RABBITMQ_PASSWORD
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"