apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consulta-api-hpa
  namespace: contatos-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consulta-contatos-api
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 