apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: contatos-app
spec:
  replicas: 1      # Banco de dados não é escalável horizontalmente (sem configuração de replica set)
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: mongodb
        # Variáveis de ambiente para configuração do MongoDB
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: MONGO_USER
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: MONGO_PASSWORD
        - name: MONGO_INITDB_DATABASE
          value: "contatos"
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db    # Montagem do volume persistente
        - name: mongo-init
          mountPath: /docker-entrypoint-initdb.d  # Scripts de inicialização
        # Verificação de saúde do MongoDB
        readinessProbe:
          exec:
            command: 
              - mongosh
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        # Recursos alocados para o MongoDB
        resources:
          limits:
            cpu: "1000m"    # Limite máximo de CPU (1 core)
            memory: "1Gi"    # Limite máximo de memória
          requests:
            cpu: "500m"     # Requisição mínima de CPU
            memory: "512Mi"  # Requisição mínima de memória
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc  # Referência ao PVC
      - name: mongo-init
        configMap:
          name: mongo-init    # ConfigMap com scripts de inicialização
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
  namespace: contatos-app
data:
  init.js: |
    db = db.getSiblingDB('contatos');
    db.createUser({
      user: 'contatos',
      pwd: 'contatos',
      roles: [
        { role: 'readWrite', db: 'contatos' }
      ]
    }); 