apiVersion: v1
kind: Service
metadata:
  name: consulta-contatos-api
spec:
  selector:
    app: consulta-contatos-api
  ports:
  - port: 8081
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP