apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastro-contatos-api
  namespace: contatos-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cadastro-contatos-api
  template:
    metadata:
      labels:
        app: cadastro-contatos-api
    spec:
      containers:
      - name: cadastro-contatos-api
        image: pedrobaraof/cadastro-contatos-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: POSTGRES_CONNECTION
        - name: RabbitMQ__Host
          value: "rabbitmq"
        - name: RabbitMQ__Username
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: RABBITMQ_USER
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: RABBITMQ_PASSWORD
        resources:
          limits:
            cpu: "500m"    # 500 milicores = 0.5 CPU
            memory: "512Mi"
          requests:
            cpu: "200m"    # 200 milicores = 0.2 CPU
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cadastro-contatos-api
  namespace: contatos-app
spec:
  selector:
    app: cadastro-contatos-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP 