apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cadastro-api-hpa
  namespace: contatos-app
spec:
  scaleTargetRef: # Seleciona o Deployment que será escalado
    apiVersion: apps/v1
    kind: Deployment
    name: cadastro-contatos-api
  minReplicas: 1 # Número mínimo de réplicas
  maxReplicas: 2 # Número máximo de réplicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Escala quando o uso médio de CPU atinge 70% 