apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cadastro-api-hpa
  namespace: contatos-app
spec:
  # Referência ao Deployment que será escalado
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cadastro-contatos-api
  minReplicas: 2    # Número mínimo de réplicas
  maxReplicas: 3    # Número máximo de réplicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70    # Escala quando o uso médio de CPU atinge 70% 