name: Build and Publish Docker Images

on:
  workflow_run:
    workflows: ["Test"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: cadastro
            image: pedrobaraof/fiap.5nett.contatos-cadastro
            dockerfile: ./src/Services/Contatos.Cadastro.Api/Dockerfile
            context: .
          - service: consulta
            image: pedrobaraof/fiap.5nett.contatos-consulta
            dockerfile: ./src/Services/Contatos.Consulta.Api/Dockerfile
            context: .
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image (sha)
        id: build-sha
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ matrix.image }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository }}

      - name: Push latest tag (only on main)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ matrix.image }}:latest
