{
 "title": "Contatos API - Cadastro",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "description": "Indica o tempo de início do processo da aplicação.",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"cadastro-contatos-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Liveness",
   "type": "stat",
   "description": "Status da aplicação (Unhealthy, Degraded, Healthy)",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{job=\"cadastro-contatos-api\", healthcheck=\"self\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "stat",
   "description": "Indica se a aplicação está pronta para receber requições (Unhealthy, Degraded, Healthy)",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{job=\"cadastro-contatos-api\", healthcheck=\"npgsql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "description": "Consumo de CPU pela aplicação",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"cadastro-contatos-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM (MB)",
   "type": "stat",
   "description": "Quantidade de memória RAM consumida pela aplicação",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"cadastro-contatos-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Utilização de CPU",
   "type": "timeseries",
   "description": "Uso de CPU pela aplicação",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"cadastro-contatos-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumo de RAM",
   "type": "timeseries",
   "description": "Quantidade de memória RAM consumida pela aplicação",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"cadastro-contatos-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições HTTP por status code",
   "type": "timeseries",
   "description": "Contagem total de requisições HTTP recebidas, agrupadas por código de status.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(code) (increase(http_requests_received_total{job=\"cadastro-contatos-api\", method=\"POST\",endpoint=\"/api/contatos/\"}[30s]))",
     "legendFormat": "HTTP {{code}}"
    },
    {
     "expr": "sum by(code) (increase(http_requests_received_total{job=\"cadastro-contatos-api\", method=\"PUT\",endpoint=\"/api/contatos/{id}\"}[30s]))",
     "legendFormat": "HTTP {{code}}"
    },
    {
     "expr": "sum by(code) (increase(http_requests_received_total{job=\"cadastro-contatos-api\", method=\"DELETE\",endpoint=\"/api/contatos/{id}\"}[30s]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Latência das requisições",
   "type": "timeseries",
   "description": "Latência das requisições",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(http_request_duration_seconds_sum{job=\"cadastro-contatos-api\", method=\"POST\",endpoint=\"/api/contatos/\"}[30s])) / sum by(endpoint) (rate(http_request_duration_seconds_count{job=\"cadastro-contatos-api\", method=\"POST\",endpoint=\"/api/contatos/\"}[30s]))",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "sum by(endpoint) (rate(http_request_duration_seconds_sum{job=\"cadastro-contatos-api\", method=\"PUT\",endpoint=\"/api/contatos/{id}\"}[30s])) / sum by(endpoint) (rate(http_request_duration_seconds_count{job=\"cadastro-contatos-api\", method=\"PUT\",endpoint=\"/api/contatos/{id}\"}[30s]))",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "sum by(endpoint) (rate(http_request_duration_seconds_sum{job=\"cadastro-contatos-api\", method=\"DELETE\",endpoint=\"/api/contatos/{id}\"}[30s])) / sum by(endpoint) (rate(http_request_duration_seconds_count{job=\"cadastro-contatos-api\", method=\"DELETE\",endpoint=\"/api/contatos/{id}\"}[30s]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}