{
 "title": "Contatos API",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status HTTP por Respostas",
   "type": "timeseries",
   "description": "Status Code por Respostas da API de Contatos",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(code) (increase(http_requests_received_total{job=\"contatos-api\", controller=\"Contato\", action=\"Listar\"}[30s]))",
     "legendFormat": "HTTP {{code}}"
    },
    {
     "expr": "sum by(code) (increase(http_requests_received_total{job=\"contatos-api\", controller=\"Contato\", action=\"Obter\"}[30s]))",
     "legendFormat": "HTTP {{code}}"
    },
    {
     "expr": "sum by(code) (increase(http_requests_received_total{job=\"contatos-api\", controller=\"Contato\", action=\"Criar\"}[30s]))",
     "legendFormat": "HTTP {{code}}"
    },
    {
     "expr": "sum by(code) (increase(http_requests_received_total{job=\"contatos-api\", controller=\"Contato\", action=\"Atualizar\"}[30s]))",
     "legendFormat": "HTTP {{code}}"
    },
    {
     "expr": "sum by(code) (increase(http_requests_received_total{job=\"contatos-api\", controller=\"Contato\", action=\"Excluir\"}[30s]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Utilização de RAM",
   "type": "timeseries",
   "description": "Utilização de RAM da API de Contatos",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"contatos-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilização de CPU",
   "type": "timeseries",
   "description": "Utilização de CPU da API de Contatos",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"contatos-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}